services:
  frontend:
    container_name: cma-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm_store:/root/.local/share/pnpm/store/v3
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    command: pnpm dev --host
    env_file:
      - .env

volumes:
  pnpm_store:

